import type { AgentConfig } from '@aglit-ai/types';
import {
  ANTHROPIC_LUCAS_AGENT,
  ANTHROPIC_REDDIT_AGENT,
  ANTHROPIC_RL_AGENT,
  ANTHROPIC_SOTA_AGENT,
} from './anthropic-lucas-agent.js';
import {
  ANTHROPIC_SEARCH_EVAL_BASELINE_NO_TOOLS_AGENT,
  ANTHROPIC_SEARCH_EVAL_HALLUCINATION_AUDIT_AGENT,
  ANTHROPIC_SEARCH_EVAL_PRIMARY_GRADER_AGENT,
  ANTHROPIC_SEARCH_EVAL_RUNNER_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_CHAMPION_COMBINED_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_DISAMBIGUATE_CALIBRATE_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_EVIDENCE_FIRST_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_HEAVY_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_MINIMAL_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_SEARCH_POLICY_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_VERBATIM_AGENT,
} from './anthropic-search-eval-agents.js';

export * from './anthropic-lucas-agent.js';
export * from './anthropic-search-eval-agents.js';

export const ANTHROPIC_AGENTS: AgentConfig[] = [
  ANTHROPIC_LUCAS_AGENT,
  ANTHROPIC_REDDIT_AGENT,
  ANTHROPIC_SOTA_AGENT,
  ANTHROPIC_RL_AGENT,
  ANTHROPIC_SEARCH_EVAL_BASELINE_NO_TOOLS_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_MINIMAL_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_VERBATIM_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_SEARCH_POLICY_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_EVIDENCE_FIRST_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_DISAMBIGUATE_CALIBRATE_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_HEAVY_AGENT,
  ANTHROPIC_SEARCH_EVAL_WIKI_CHAMPION_COMBINED_AGENT,
  ANTHROPIC_SEARCH_EVAL_PRIMARY_GRADER_AGENT,
  ANTHROPIC_SEARCH_EVAL_HALLUCINATION_AUDIT_AGENT,
  ANTHROPIC_SEARCH_EVAL_RUNNER_AGENT,
];
